# Берем легкую версию Python
FROM python:3.12-slim

# Устанавливаем рабочую папку внутри контейнера
WORKDIR /app

# Копируем список зависимостей и ставим их
COPY dashboard/requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Копируем наши файлы в контейнер
COPY dashboard dashboard/
COPY .streamlit .streamlit/
COPY main.py .

# Запускаем основной файл
CMD ["streamlit", "run", "main.py"]